---
- name: Create config direcotires
  hosts: DC1, DC2
  tasks:
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: "{{lookup('env','PWD')}}/configs/dynamic/{{inventory_hostname}}/"
      state: directory