---
- hosts: DC1, DC2
  name: Upload all configs
  tasks:
  - name: Upload all interface configurations
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/final/{{inventory_hostname}}_FINAL.cfg"
      replace: config
      save_when: always